name: pa
channels:
  - https://conda.anaconda.org/soft-matter
  - https://conda.anaconda.org/conda-forge
dependencies:
- jupyter
- matplotlib
- numpy=1.10.1
- pandas=0.17.0
- pims=0.3.2
- pip
- python=3.4.3
- pyyaml=3.11
- scikit-image=0.11.3
- scipy=0.16.0
- statsmodels=0.6.1
- tifffile=0.3.1
- pip:
  - lmfit==0.8.3
